package DAO.pojo;
// default package
// Generated 2016-9-6 21:09:16 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BenchdataAccurate generated by hbm2java
 */
@Entity
@Table(name = "benchdata_accurate", catalog = "superquant")
public class BenchdataAccurate implements java.io.Serializable {

	private BenchdataAccurateId id;
	private double price;

	public BenchdataAccurate() {
	}

	public BenchdataAccurate(BenchdataAccurateId id, double price) {
		this.id = id;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "benchId", column = @Column(name = "benchId", nullable = false, length = 20)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 19)) })
	public BenchdataAccurateId getId() {
		return this.id;
	}

	public void setId(BenchdataAccurateId id) {
		this.id = id;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
