package DAO.pojo;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IndustriesId generated by hbm2java
 */
@Embeddable
public class IndustriesId implements java.io.Serializable {

	private String industry;
	private String date;

	public IndustriesId() {
	}

	public IndustriesId(String industry, String date) {
		this.industry = industry;
		this.date = date;
	}

	@Column(name = "industry", nullable = false, length = 20)
	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	@Column(name = "date", nullable = false, length = 20)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IndustriesId))
			return false;
		IndustriesId castOther = (IndustriesId) other;

		return ((this.getIndustry() == castOther.getIndustry()) || (this.getIndustry() != null
				&& castOther.getIndustry() != null && this.getIndustry().equals(castOther.getIndustry())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIndustry() == null ? 0 : this.getIndustry().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
