package DAO.pojo;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Industries generated by hbm2java
 */
@Entity
@Table(name = "industries", catalog = "superquant")
public class Industries implements java.io.Serializable {

	private IndustriesId id;
	private int company;
	private double averagePrice;
	private double riseFall;
	private double volume;
	private double turnover;
	private double inflows;
	private String leaderstock;
	private double price;
	private double stockRiseFall;

	public Industries() {
	}

	public Industries(IndustriesId id, int company, double averagePrice, double riseFall, double volume,
			double turnover, double inflows, String leaderstock, double price, double stockRiseFall) {
		this.id = id;
		this.company = company;
		this.averagePrice = averagePrice;
		this.riseFall = riseFall;
		this.volume = volume;
		this.turnover = turnover;
		this.inflows = inflows;
		this.leaderstock = leaderstock;
		this.price = price;
		this.stockRiseFall = stockRiseFall;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "industry", column = @Column(name = "industry", nullable = false, length = 20) ),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 20) ) })
	public IndustriesId getId() {
		return this.id;
	}

	public void setId(IndustriesId id) {
		this.id = id;
	}

	@Column(name = "company", nullable = false)
	public int getCompany() {
		return this.company;
	}

	public void setCompany(int company) {
		this.company = company;
	}

	@Column(name = "average_price", nullable = false, precision = 22, scale = 0)
	public double getAveragePrice() {
		return this.averagePrice;
	}

	public void setAveragePrice(double averagePrice) {
		this.averagePrice = averagePrice;
	}

	@Column(name = "rise_fall", nullable = false, precision = 22, scale = 0)
	public double getRiseFall() {
		return this.riseFall;
	}

	public void setRiseFall(double riseFall) {
		this.riseFall = riseFall;
	}

	@Column(name = "volume", nullable = false, precision = 22, scale = 0)
	public double getVolume() {
		return this.volume;
	}

	public void setVolume(double volume) {
		this.volume = volume;
	}

	@Column(name = "turnover", nullable = false, precision = 22, scale = 0)
	public double getTurnover() {
		return this.turnover;
	}

	public void setTurnover(double turnover) {
		this.turnover = turnover;
	}

	@Column(name = "inflows", nullable = false, precision = 22, scale = 0)
	public double getInflows() {
		return this.inflows;
	}

	public void setInflows(double inflows) {
		this.inflows = inflows;
	}

	@Column(name = "leaderstock", nullable = false, length = 20)
	public String getLeaderstock() {
		return this.leaderstock;
	}

	public void setLeaderstock(String leaderstock) {
		this.leaderstock = leaderstock;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "stock_rise_fall", nullable = false, precision = 22, scale = 0)
	public double getStockRiseFall() {
		return this.stockRiseFall;
	}

	public void setStockRiseFall(double stockRiseFall) {
		this.stockRiseFall = stockRiseFall;
	}

}
