package DAO.pojo;
// default package
// Generated 2016-9-6 21:09:16 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Simulation generated by hbm2java
 */
@Entity
@Table(name = "simulation", catalog = "superquant")
public class Simulation implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String stockId;
	private Date time;
	private double price;
	private long volume;

	public Simulation() {
	}

	public Simulation(String userId, String stockId, Date time, double price, long volume) {
		this.userId = userId;
		this.stockId = stockId;
		this.time = time;
		this.price = price;
		this.volume = volume;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userId", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "stockId", nullable = false, length = 20)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "volume", nullable = false)
	public long getVolume() {
		return this.volume;
	}

	public void setVolume(long volume) {
		this.volume = volume;
	}

}
