package DAO.pojo;
// default package
// Generated 2016-9-10 14:49:20 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SimulationProfit generated by hbm2java
 */
@Entity
@Table(name = "simulation_profit", catalog = "superquant")
public class SimulationProfit implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String stockId;
	private double profit;
	private String operation;
	private String state;
	private Date time;

	public SimulationProfit() {
		state="DISPLAY";
	}

	public SimulationProfit(String userId, String stockId, double profit, String operation, String state) {
		this.userId = userId;
		this.stockId = stockId;
		this.profit = profit;
		this.operation = operation;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userId", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "stockId", nullable = false, length = 20)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	@Column(name = "profit", nullable = false, precision = 22, scale = 0)
	public double getProfit() {
		return this.profit;
	}

	public void setProfit(double profit) {
		this.profit = profit;
	}

	@Column(name = "operation", nullable = false, length = 20)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "state", nullable = false, length = 20, columnDefinition="varchar(20) default 'DISPLAY'")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "time", nullable = false, length = 19)
	public Date getDate() {
		return this.time;
	}

	public void setDate(Date time) {
		this.time = time;
	}
}
