package DAO.pojo;
// default package
// Generated 2016-9-6 21:09:16 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Simulationprofit generated by hbm2java
 */
@Entity
@Table(name = "simulationprofit", catalog = "superquant")
public class Simulationprofit implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String stockId;
	private Date buyTime;
	private Date sellTime;
	private double profit;

	public Simulationprofit() {
	}

	public Simulationprofit(String userId, String stockId, Date buyTime, Date sellTime, double profit) {
		this.userId = userId;
		this.stockId = stockId;
		this.buyTime = buyTime;
		this.sellTime = sellTime;
		this.profit = profit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userId", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "stockId", nullable = false, length = 20)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "buyTime", nullable = false, length = 19)
	public Date getBuyTime() {
		return this.buyTime;
	}

	public void setBuyTime(Date buyTime) {
		this.buyTime = buyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sellTime", nullable = false, length = 19)
	public Date getSellTime() {
		return this.sellTime;
	}

	public void setSellTime(Date sellTime) {
		this.sellTime = sellTime;
	}

	@Column(name = "profit", nullable = false, precision = 22, scale = 0)
	public double getProfit() {
		return this.profit;
	}

	public void setProfit(double profit) {
		this.profit = profit;
	}

}
