package DAO.pojo;
// default package
// Generated 2016-9-6 21:09:16 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TradeRecordAccurateId generated by hbm2java
 */
@Embeddable
public class TradeRecordAccurateId implements java.io.Serializable {

	private String stockId;
	private Date date;

	public TradeRecordAccurateId() {
	}

	public TradeRecordAccurateId(String stockId, Date date) {
		this.stockId = stockId;
		this.date = date;
	}

	@Column(name = "stockId", nullable = false, length = 20)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TradeRecordAccurateId))
			return false;
		TradeRecordAccurateId castOther = (TradeRecordAccurateId) other;

		return ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
				&& castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
