package DAO.pojo;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TradeRecord generated by hbm2java
 */
@Entity
@Table(name = "trade_record", catalog = "superquant")
public class TradeRecord implements java.io.Serializable {

	private TradeRecordId id;
	private double open;
	private double close;
	private double high;
	private double low;
	private double adjPrice;
	private long volume;
	private double turnover;
	private double pe;
	private double pb;

	public TradeRecord() {
	}

	public TradeRecord(TradeRecordId id, double open, double close, double high, double low, double adjPrice,
			long volume, double turnover, double pe, double pb) {
		this.id = id;
		this.open = open;
		this.close = close;
		this.high = high;
		this.low = low;
		this.adjPrice = adjPrice;
		this.volume = volume;
		this.turnover = turnover;
		this.pe = pe;
		this.pb = pb;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "stockId", column = @Column(name = "stockID", nullable = false, length = 20) ),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 20) ) })
	public TradeRecordId getId() {
		return this.id;
	}

	public void setId(TradeRecordId id) {
		this.id = id;
	}

	@Column(name = "open", nullable = false, precision = 12, scale = 0)
	public double getOpen() {
		return this.open;
	}

	public void setOpen(double open) {
		this.open = open;
	}

	@Column(name = "close", nullable = false, precision = 22, scale = 0)
	public double getClose() {
		return this.close;
	}

	public void setClose(double close) {
		this.close = close;
	}

	@Column(name = "high", nullable = false, precision = 22, scale = 0)
	public double getHigh() {
		return this.high;
	}

	public void setHigh(double high) {
		this.high = high;
	}

	@Column(name = "low", nullable = false, precision = 22, scale = 0)
	public double getLow() {
		return this.low;
	}

	public void setLow(double low) {
		this.low = low;
	}

	@Column(name = "adj_price", nullable = false, precision = 22, scale = 0)
	public double getAdjPrice() {
		return this.adjPrice;
	}

	public void setAdjPrice(double adjPrice) {
		this.adjPrice = adjPrice;
	}

	@Column(name = "volume", nullable = false)
	public long getVolume() {
		return this.volume;
	}

	public void setVolume(long volume) {
		this.volume = volume;
	}

	@Column(name = "turnover", nullable = false, precision = 22, scale = 0)
	public double getTurnover() {
		return this.turnover;
	}

	public void setTurnover(double turnover) {
		this.turnover = turnover;
	}

	@Column(name = "pe", nullable = false, precision = 22, scale = 0)
	public double getPe() {
		return this.pe;
	}

	public void setPe(double pe) {
		this.pe = pe;
	}

	@Column(name = "pb", nullable = false, precision = 22, scale = 0)
	public double getPb() {
		return this.pb;
	}

	public void setPb(double pb) {
		this.pb = pb;
	}

}
