package DAO.pojo;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserStrategyId generated by hbm2java
 */
@Embeddable
public class UserStrategyId implements java.io.Serializable {

	private String userId;
	private String stockId;
	private String strategyName;

	public UserStrategyId() {
	}

	public UserStrategyId(String userId, String stockId, String strategyName) {
		this.userId = userId;
		this.stockId = stockId;
		this.strategyName = strategyName;
	}

	@Column(name = "userID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "stockID", nullable = false, length = 20)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	@Column(name = "strategyName", nullable = false, length = 20)
	public String getStrategyName() {
		return this.strategyName;
	}

	public void setStrategyName(String strategyName) {
		this.strategyName = strategyName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserStrategyId))
			return false;
		UserStrategyId castOther = (UserStrategyId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
						&& castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())))
				&& ((this.getStrategyName() == castOther.getStrategyName())
						|| (this.getStrategyName() != null && castOther.getStrategyName() != null
								&& this.getStrategyName().equals(castOther.getStrategyName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
		result = 37 * result + (getStrategyName() == null ? 0 : this.getStrategyName().hashCode());
		return result;
	}

}
