package DAO.pojo;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserStockId generated by hbm2java
 */
@Embeddable
public class UserStockId implements java.io.Serializable {

	private String userName;
	private String stockId;

	public UserStockId() {
	}

	public UserStockId(String userName, String stockId) {
		this.userName = userName;
		this.stockId = stockId;
	}

	@Column(name = "userName", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "stockID", nullable = false, length = 20)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserStockId))
			return false;
		UserStockId castOther = (UserStockId) other;

		return ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
				&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
						&& castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
		return result;
	}

}
