package DAO.pojo;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserStrategy generated by hbm2java
 */
@Entity
@Table(name = "user_strategy", catalog = "superquant")
public class UserStrategy implements java.io.Serializable {

	private UserStrategyId id;

	public UserStrategy() {
	}

	public UserStrategy(UserStrategyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userName", column = @Column(name = "userName", nullable = false, length = 20) ),
			@AttributeOverride(name = "strategy", column = @Column(name = "strategy", nullable = false, length = 20) ) })
	public UserStrategyId getId() {
		return this.id;
	}

	public void setId(UserStrategyId id) {
		this.id = id;
	}

}
