package DAO.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "superquant")
public class User implements java.io.Serializable {

	private String username;
	private String userpassword;
	private String createDate;

	public User() {
	}

	public User(String username) {
		this.username = username;
	}

	public User(String username, String userpassword, String createDate) {
		this.username = username;
		this.userpassword = userpassword;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "userpassword", length = 20)
	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	@Column(name = "createDate", length = 20)
	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

}
