package DAO.pojo;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserStrategyId generated by hbm2java
 */
@Embeddable
public class UserStrategyId implements java.io.Serializable {

	private String userName;
	private String strategy;

	public UserStrategyId() {
	}

	public UserStrategyId(String userName, String strategy) {
		this.userName = userName;
		this.strategy = strategy;
	}

	@Column(name = "userName", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "strategy", nullable = false, length = 20)
	public String getStrategy() {
		return this.strategy;
	}

	public void setStrategy(String strategy) {
		this.strategy = strategy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserStrategyId))
			return false;
		UserStrategyId castOther = (UserStrategyId) other;

		return ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
				&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getStrategy() == castOther.getStrategy()) || (this.getStrategy() != null
						&& castOther.getStrategy() != null && this.getStrategy().equals(castOther.getStrategy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getStrategy() == null ? 0 : this.getStrategy().hashCode());
		return result;
	}

}
