package testobject;
// Generated 2016-5-20 23:45:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserStockId generated by hbm2java
 */
@Embeddable
public class UserStockId implements java.io.Serializable {

	private int userId;
	private String stockId;

	public UserStockId() {
	}

	public UserStockId(int userId, String stockId) {
		this.userId = userId;
		this.stockId = stockId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "stockID", nullable = false, length = 20)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserStockId))
			return false;
		UserStockId castOther = (UserStockId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
						&& castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
		return result;
	}

}
