package testobject;
// Generated 2016-5-20 23:45:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserStrategyId generated by hbm2java
 */
@Embeddable
public class UserStrategyId implements java.io.Serializable {

	private int userId;
	private String strategy;

	public UserStrategyId() {
	}

	public UserStrategyId(int userId, String strategy) {
		this.userId = userId;
		this.strategy = strategy;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "strategy", nullable = false, length = 20)
	public String getStrategy() {
		return this.strategy;
	}

	public void setStrategy(String strategy) {
		this.strategy = strategy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserStrategyId))
			return false;
		UserStrategyId castOther = (UserStrategyId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getStrategy() == castOther.getStrategy()) || (this.getStrategy() != null
						&& castOther.getStrategy() != null && this.getStrategy().equals(castOther.getStrategy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getStrategy() == null ? 0 : this.getStrategy().hashCode());
		return result;
	}

}
